name: Commit Validation
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Environment Setup
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Installing Packages
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
