name: NPM Publish
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Environment Setup
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Installing Packages
        run: npm install
      - name: Build
        run: npm run build
      - name : NPM Publish
        run: npm publish
        working-directory: ./dist/ng-app-insights
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
